stages:
    data_ingestion:
      cmd: python src/data_ingestion.py
      deps:
      - src/data_ingestion.py
     
      outs: 
      - data/data
    data_splitting:
      cmd: python src/data_splitting.py
      deps:
      - data/data
      - src/data_splitting.py
       params:
      - data_splitting.test_size
      outs:
      - data/raw
    data_preprocessing:
      cmd: python src/data_preprocessing.py
      deps:
      - src/data_ingestion.py
      - data/raw
      outs:
      - data/processed
    feature_engineering:
      cmd: python src/feature_engineering.py
      deps:
      - data/processed
      - src/feature_engineering.py
      outs:
      - data/features
    model_building:
      cmd: python src/model_building.py
      deps:
      - data/features
      - src/model_building.py
      outs:
      - model
    model_evaluation:
      cmd: python src/model_evaluation.py
      deps:
      - model
      - src/model_evaluation.py
      outs:
      - metrics
# name:
# CMD
