stages:
    data_ingestion:
      cmd: python src/data_ingestion.py
      deps:
      - src/data_ingestion.py
      outs: 
      - data/raw
    data_preprocessing:
      cmd: python src/data_preprocessing.py
      deps:
      - src/data_ingestion.py
      - data/raw
      outs:
      - data/processed
# name:
# CMD
